test change yaml

diff --git a/.github/workflows/front.yaml b/.github/workflows/front.yaml
--- a/.github/workflows/front.yaml
+++ b/.github/workflows/front.yaml
@@ -26,13 +26,20 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: "20.x"
-          cache: "npm"
+
+      - name: Debug node_modules
+        run: |
+          ls -la node_modules/@rollup || echo "@rollup not found"
+          ls -la node_modules/@beetpack || echo "@beetpack not found"
 
       - name: Install dependencies
-        run: npm ci
+        run: |
+          npm ci
+          npm install @rollup/rollup-linux-x64-gnu --no-save
 
       - name: Run tests
         run: npm test -- --watchAll=false
+
 
       - name: Build application
         run: npm run build
